---
name: "CRDA Scan"
"on":
  workflow_call:
    secrets:
      CRDA_KEY:
        required: false
      SNYK_TOKEN:
        required: false
  workflow_dispatch: null
  pull_request_target:
    branches:
    - "master"
    types:
    - "assigned"
    - "opened"
    - "synchronize"
    - "reopened"
    - "labeled"
    - "edited"
permissions:
  contents: "read"
jobs:
  crda-scan:
    permissions:
      contents: "read"
      security-events: "write"
    name: "Scan project vulnerabilities with CRDA"
    runs-on: "ubuntu-20.04"
    steps:
    - name: "Check out repository"
      uses: "actions/checkout@v2"
    - name: "Install CRDA CLI"
      uses: "redhat-actions/openshift-tools-installer@v1"
      with:
        source: "github"
        github_pat: "${{ github.token }}"
        crda: "latest"
    - name: "CRDA Scan"
      id: "scan"
      uses: "redhat-actions/crda@v1"
      with:
        snyk_token: "${{ secrets.SNYK_TOKEN }}"
